import { NextRequest, NextResponse } from "next/server";
import { requireUser, unauthorized } from "@/lib/auth";
import { FLEET_INVENTORY, getSlugs } from "@/lib/fleet";
import fs from "fs";
import path from "path";

export const runtime = "nodejs";

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export async function POST(req: NextRequest) {
  try {
    await requireUser();
  } catch {
    return unauthorized();
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const b = body as { slug?: string; ideaId?: string; ideaSlug?: string; targetSlug?: string };
  const slug = (b.slug ?? b.ideaSlug ?? "").trim();
  const ideaId = (b.ideaId ?? "").trim();
  if (!slug || !SLUG_RE.test(slug) || slug.length < 3 || slug.length > 48) {
    return NextResponse.json(
      { error: "Invalid slug: use lowercase kebab-case, 3-48 chars, e.g. my-dashboard" },
      { status: 400 }
    );
  }

  const existing = getSlugs();
  if (existing.has(slug)) {
    return NextResponse.json({ error: `Slug already exists in fleet inventory: ${slug}` }, { status: 409 });
  }

  // Resolve idea for kind/target context if provided
  const idea = FLEET_INVENTORY.find((p) => p.slug === b.targetSlug) || null;
  // Find FleetIdea kind if ideaId given — look up from fleet lib dynamically by importing lazily would be circular, so just echo kind from body if present
  const kind = (b as unknown as { kind?: string }).kind === "enhancement" ? "enhancement" as const : "new" as const;
  const targetSlug = (b.targetSlug ?? "").trim() || undefined;

  const isVercel = process.env.VERCEL === "1";
  const baseDir = isVercel ? "/tmp" : "/root/projects";
  const targetDir = path.join(baseDir, slug);

  if (fs.existsSync(targetDir)) {
    return NextResponse.json({ error: `Directory already exists: ${targetDir}` }, { status: 409 });
  }

  // Prevent path traversal (already validated by regex, but double-check)
  const resolved = path.resolve(targetDir);
  if (!resolved.startsWith(path.resolve(baseDir) + path.sep)) {
    return NextResponse.json({ error: "Invalid path" }, { status: 400 });
  }

  try {
    fs.mkdirSync(targetDir, { recursive: true });

    const pkg = {
      name: slug,
      version: "0.1.0",
      private: true,
      description: `Fleet scaffold for ${slug} — generated by fleet-ideas-lab${ideaId ? ` (${ideaId})` : ""}${kind === "enhancement" && targetSlug ? ` as enhancement for ${targetSlug}` : ""}`,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        next: "16.2.11",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
    };

    fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");

    const readme = `# ${slug}
${kind === "enhancement" && targetSlug ? `> Enhancement for \`${targetSlug}\` — scaffold as feature tab inside \`${targetSlug}\`, not a standalone project.` : `> New dashboard — white-space (no existing dashboard covers this domain\u00d7capability).`}
Scaffolded by fleet-ideas-lab — POST /api/fleet/scaffold
${ideaId ? `- Idea: ${ideaId}\n` : ""}${targetSlug ? `- Target: ${targetSlug}\n` : ""}- Kind: ${kind}
- Inventory: not yet registered in fleet (add to src/lib/fleet.ts when verified via vercel).
- Data sources: TBD (vault) — no invented values.
- Next steps: \`npm install\` then implement per idea spec. On Vercel this dir is ephemeral (/tmp) — clone to /root/projects/${slug} on your dev server.
Generated: ${new Date().toISOString()}
Mode: ${isVercel ? "vercel-tmp (ephemeral)" : "hostinger-persisted"}
`;
    fs.writeFileSync(path.join(targetDir, "README.md"), readme, "utf8");
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error("[scaffold] failed", { slug, baseDir, error: msg });
    // Clean up partial dir if created
    try { if (fs.existsSync(targetDir) && isVercel) fs.rmSync(targetDir, { recursive: true, force: true }); } catch {}
    return NextResponse.json({ error: `Scaffold failed: ${msg} — ${isVercel ? "on Vercel /tmp is ephemeral; check Vercel logs" : "check /root/projects permissions"}` }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    slug,
    dir: targetDir,
    ideaId: ideaId || undefined,
    kind,
    targetSlug,
    mode: isVercel ? "vercel-tmp" : "hostinger-persisted",
    note: isVercel ? "Preview scaffold in /tmp — ephemeral; clone to /root/projects/<slug> on your dev server" : "Persisted at /root/projects/<slug> on dev server",
  });
}
