import { NextRequest, NextResponse } from "next/server";
import { requireUser, unauthorized } from "@/lib/auth";
import { getSlugs } from "@/lib/fleet";
import fs from "fs";
import path from "path";

export const runtime = "nodejs";

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export async function POST(req: NextRequest) {
  try {
    await requireUser();
  } catch {
    return unauthorized();
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const b = body as { slug?: string; ideaId?: string; ideaSlug?: string };
  const slug = (b.slug ?? b.ideaSlug ?? "").trim();
  const ideaId = (b.ideaId ?? "").trim();
  if (!slug || !SLUG_RE.test(slug) || slug.length < 3 || slug.length > 48) {
    return NextResponse.json(
      { error: "Invalid slug: use lowercase kebab-case, 3-48 chars, e.g. my-dashboard" },
      { status: 400 }
    );
  }

  const existing = getSlugs();
  if (existing.has(slug)) {
    return NextResponse.json({ error: `Slug already exists in fleet inventory: ${slug}` }, { status: 409 });
  }

  const baseDir = "/root/projects";
  const targetDir = path.join(baseDir, slug);

  if (fs.existsSync(targetDir)) {
    return NextResponse.json({ error: `Directory already exists: ${targetDir}` }, { status: 409 });
  }

  // Prevent path traversal (already validated by regex, but double-check)
  const resolved = path.resolve(targetDir);
  if (!resolved.startsWith(path.resolve(baseDir) + path.sep)) {
    return NextResponse.json({ error: "Invalid path" }, { status: 400 });
  }

  fs.mkdirSync(targetDir, { recursive: true });

  const pkg = {
    name: slug,
    version: "0.1.0",
    private: true,
    description: `Fleet scaffold for ${slug} — generated by fleet-ideas-lab`,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      typecheck: "tsc --noEmit",
    },
    dependencies: {
      next: "16.2.11",
      react: "19.2.4",
      "react-dom": "19.2.4",
    },
  };

  fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");

  const readme = `# ${slug}

Scaffolded by fleet-ideas-lab — /api/fleet/scaffold
${ideaId ? `- Idea: ${ideaId}\n` : ""}- Inventory: not yet registered in fleet (add to src/lib/fleet.ts when verified via vercel).
- Data sources: TBD (vault) — no invented values.
- Next steps: \`npm install\` then implement per idea spec.

Generated: ${new Date().toISOString()}
`;
  fs.writeFileSync(path.join(targetDir, "README.md"), readme, "utf8");

  return NextResponse.json({ ok: true, slug, dir: targetDir, ideaId: ideaId || undefined });
}
